### ISSUE TITLE
UI issues on the Export variance data page.

### ISSUE THREAD

**Issue by kgorana** [bcgov/bcparks-ar-admin#258]
**Description**

How to replicate:
* Navigate to the A&R Admin on the test environment: [A&R Admin](https://d3ahrzu0mpndj3.cloudfront.net/export-reports)
* Navigate to the tab `Variance`

**Expected Behavior:**
* Should resemble the design mockups.

**Issues:**
1. The label “Fiscal Year” should be displayed as “Fiscal year”, the second word starts with a lowercase letter. 
2. The default message on the date picker reads “Select fiscal year end” instead of “Select fiscal year”

**Environment**
None

**Attachments**
![image](https://github.com/bcgov/bcparks-ar-admin/assets/145403218/98ab99a3-26e6-4285-a91f-3b67e3b93b1f)

**Linked issues**
blocks
- [ ] #257

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this issue has been fixed.
