### ISSUE TITLE
[S] Implement an option to clear out the Date on Data review page

### ISSUE THREAD

**Issue by kgorana** [bcgov/bcparks-ar-admin#260]
## Description
This ticket is to implement an option to clear out the `Date` from the Data review page filters so users can filter variances without a date filter even after using the `Data` filter for a different filtration. 

## Acceptance Criteria

An option to clear the `Date` field should be present. 

## Notes
![Image](https://github.com/bcgov/bcparks-ar-admin/assets/145403218/2c9dd710-81de-4cb4-a213-444b8300a8ec)

## Linked issues
- [x] ~https://bcparksdigital.atlassian.net/browse/BRS-1194~

**Comment by davidclaveau** [comment]
@manuji ready for review in DEV! This ticket just adds that reset 'X' to the Date input on the Review Data page - it was missing on the page's first load. Thanks!

![Image](https://github.com/bcgov/bcparks-ar-admin/assets/62899351/3967ccaa-e188-4174-b2db-e5c601b9569c)

**Comment by manuji** [comment]
Tested on TEST: **Pending**
* Verified that the option to clear the date field is present and functioning. 

**Issue:**
* After I clear out the Date filter, the option to "Filter" does not function. In other words, we cannot filter results or retrieve data without a date filter. Refer to the video. 
 


https://github.com/bcgov/bcparks-ar-admin/assets/65190263/615a8618-7dda-430a-b918-d7831209a3bf

Passing this back to To Do @davidclaveau . FYI @JLWade

**Comment by manuji** [comment]
Hi @JLWade , I want to confirm the business requirement related to the above filter. Do you think there will be a need to filter results without a "date"? 

If not I can pass this ticket as the option to clear the date filter has been implemented, but again not sure why we need a clear option for the date field if we cannot filter results without a date filter.

**Comment by Dianadec** [comment]
@JLWade  following up :)

**Comment by JLWade** [comment]
You are correct @manuji that you cannot filter unless the date is present - I think we can move this to PO review as is to make it easier to select a new date. However - I think we may need to inquire about if filtering without a date is required - the ticket is old from Jira and I think missing some context that I cannot remember now.

**Comment by manuji** [comment]
Thank you Jess for the feedback. I will move this ticket along. If the client feel the need to have a filter option without the date, then we can have a new ticket and then work on it in future.

Moving to PO review. @meyerdarcie

**Comment by meyerdarcie** [comment]
Moving to done - will connect with A&R business area re: if filtering without a date is required.
