### ISSUE TITLE
Add cron job to A&R export report

### ISSUE THREAD

**Issue by kgorana** [bcgov/bcparks-ar-admin#266]
## Description
As a A&R sys admin user, I want to be able to export ALL (or close to all) A&R data quickly and without error so that I can use it in my analysis that helps determine things like APA calculations, province wide totals for capital investment team to divy up bugdet, decision making on allocating infrastructure improvements.

Currently the export report is timing out because there is too much data. With the addition of historical data it will get worse. This ticket is to create an automatic cron job that runs every evening to create the exported report that can be used for the next day.

Doing this means data in report may not be 100% up-to-date. 
>[!NOTE]
**Will need to determine timing of this** (thinking 12am every evening? then report will reflect previous days values)

## Acceptance Criteria
* cron job runs to export full A&R report **_at …. each day_**
* **_will all export reports respect this? ie. a seymour operator will use the same data from the cron job or real time if they are only exporting seymour? (my hunch is use same cron job?)_**

## Notes

**Comment by LindsayMacfarlane** [comment]
@Dianadec - I think this is one is done?
