### ISSUE TITLE
A&R - Export Report - Small typo in exporter status

### ISSUE THREAD

**Issue by kgorana** [bcgov/bcparks-ar-admin#271]
## How to replicate
* Navigate to `Export Reports` in A&R
* Trigger a generation of report and pay attention to the messaging under `Exporter status`

## Expected Behavior
The message under Exporter status should say `Fetching all entries for Sysadmin` .

## Issue
The message currently has a typo on the word `entries`. It currently says `entires`

![image](https://github.com/bcgov/bcparks-ar-admin/assets/145403218/8761546c-2683-4922-b844-585fc046d228)

**Comment by davidclaveau** [comment]
@manuji should be good for review in DEV now!

**Comment by manuji** [comment]
Tested on TEST: **Pending**
* Verified that the typo has been fixed, but I am seeing a change in the entire message displayed when the export in progress. 

Scenario:
* Sign in as a user who has "sysadmin" access and run the report. 
* Check what the message displayed while export in progress. 

Issue:
* It shows all the park IDs and sub ids as well as "sysadmin" access levels making the message very messy. Before this bug fix, if the user has only "sysadmin" access level assigned then it only displayed that and not all the individual parks:subarea ids. 



![Image](https://github.com/bcgov/bcparks-ar-admin/assets/65190263/cfc5554f-cce5-42f2-99fb-bbde6bbda6a7)


@davidclaveau , is it possible to check what made this change?

**Comment by davidclaveau** [comment]
@manuji looks like there were quite a few of those individual park roles applied to your user in Keycloak beyond just the `sysadmin` one. I removed them just now as I think that was a mistake (you should only need the one `sysadmin` role), so you should just be seeing the usual `sysadmin` when exporting now!

**Comment by manuji** [comment]
Thank you @davidclaveau . 

This ticket is ready for PO review on TEST environment.

**Comment by JLWade** [comment]
working as expected - moving to done
