### ISSUE TITLE
Add "Historical" tag to Subarea filters on Review Data page

### ISSUE THREAD

**Issue by manuji** [bcgov/bcparks-ar-admin#283]
Scenario:
* Navigate to the A&R on TEST environment.
* Login and navigate to the Review Data page
* Select a park that has Historical data
* Check the Subarea filter and see if it shows "Historical" tag for the historical subarea items. 

Expected:
* To be consistent with the Enter Data page, we should show the "Historical" tag for the historical subareas on the Review Data page. 

Issue:
* Missing the blue color "Historical" tag on the Review Data page for the Subarea filter options where applicable. 

![Image](https://github.com/bcgov/bcparks-ar-admin/assets/65190263/3a7e463f-a221-4404-bcf2-ae2885505685)

**Comment by Dianadec** [comment]
Takeaway from refinement: Should update designs with this tag piece - Manuji will work with Jane to have them updated.
https://www.figma.com/file/yoMhvO0KZvsM6qoqwuIjpt/Attendance-%26-Revenue?type=design&node-id=3572%3A19127&mode=design&t=H5f7vvmngpJH7sYu-1

cc @manuji  @janemoxd

**Comment by janemoxd** [comment]
This update should be done with @meredithom. She is the 'owner' of A&R designs at this point. @manuji @Dianadec

**Comment by davidclaveau** [comment]
@manuji should be good for review in DEV now 😄

**Comment by manuji** [comment]
Tested on TEST: **passed**
* Verified that this issue has been fixed. 
* Moving to Done. fyi @JLWade & @meyerdarcie
