### ISSUE TITLE
View details page shows values with variances

### ISSUE THREAD

**Issue by JLWade** [bcgov/bcparks-ar-admin#294]
As a park operator, I want to be able to view data I have entered into A&R and see which fields have a variance flagged/triggered,

Related to #255 and #291 

This is the read only page for A&R forms.

**Acceptance Criteria:**
- view details page in A&R matches designs
- if a variance has been triggered on a value within an activity form then it is displayed that way to the user (display shown in designs) so they know it is a variance

**Designs:**
[Figma](https://www.figma.com/file/yoMhvO0KZvsM6qoqwuIjpt/Attendance-%26-Revenue?type=design&node-id=5175-16240&mode=design&t=DYRLTdok882wdFVR-4)

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this task has been implemented and working fine. 
* Passing to PO review.

**Comment by JLWade** [comment]
working as expected mving to done
