### ISSUE TITLE
[M] A&R Research: notes field for A&R

### ISSUE THREAD

**Issue by JLWade** [bcgov/bcparks-ar-admin#333]
#### Description:

We need way to record changes to sub-areas/method of collection etc. for each park that affect long term interpretation of data. This ticket is to research how a notes field at the park level in could support long term interpretation and management of A&R data. 

#### Acceptance Criteria:

- [ ] determine how we can incorporate a notes field into the A&R tool
- [ ] write any implementation tickets for prioritization of this work and add to backlog

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocking
  - #391 
  - [Create endpoints for a Park/Subarea's Notes #378](https://github.com/bcgov/bcparks-ar-api/issues/378)

**Wireframe(s):**

**Workflows:**

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [  Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by nicolebottoms** [comment]
Wanted to add some more context to this.
This would be used at the park level, where we could add notes for changes to park reporting or spatial changes that impact reporting. An example of this would be Shuswap Marine; prior to 2022 camping data was reported under Cinnemousun Narrows Park, which is technically within Shuswap Marine Park, but the camping where it is recorded has changed.
Or Garibaldi has a few more sub areas added recently, but those sub areas also include areas of the park that aren't explicitly noted in the sub-area ie. Cheakamus sub-area not only includes Cheakamus Lake, but also Helm Creek campground and Singing Creek Campground.

**Comment by Dianadec** [comment]
@davidclaveau let me know if I can help with creating implementation/design tickets as an outcome of this exploration ticket. cc @LindsayMacfarlane

**Comment by davidclaveau** [comment]
Temporarily blocked while the team discusses how we want to save notes for a park, ie. do we want to tie a note to a Park's subarea.

For context: a simple implementation of these notes would be to store the notes data in the main `park::orcs` record in the database. But if a park has dozens of subareas (so there's a lot to contextualize or more items that branch out) then this setup won't scale efficiently in the database. So it would make more sense to break these notes out into their own records in something like `orcs::subarea::notes` and then use something like the entry date as the `sk`

**Comment by Dianadec** [comment]
need to check in with A&R Team to follow up

**Comment by LindsayMacfarlane** [comment]
@davidclaveau - I think we checked in on this earlier this week, but can you remind me if you got the answers you needed for this ticket? If you're waiting for anything let me know - happy to ping and follow up with A&R to help unblock.

**Comment by nicolebottoms** [comment]
i'm attached the standard messages that the web team uses, some are not really applicable but are a good starting point for category groupings. we may have a couple more to add that are more specific to our business needs.
[Copy of EventTypes-StandardMessages-20241016.xlsx](https://github.com/user-attachments/files/17480909/Copy.of.EventTypes-StandardMessages-20241016.xlsx)

**Comment by sallyhaynes** [comment]
I think the event types file is for ticket #361, rather than #333.

**Comment by davidclaveau** [comment]
> @davidclaveau - I think we checked in on this earlier this week, but can you remind me if you got the answers you needed for this ticket? If you're waiting for anything let me know - happy to ping and follow up with A&R to help unblock.

This is unblocked! The A&R team gave some insight on how they would like the Notes categorized, it's just fallen down in the order because higher priority tickets have cropped up and taken precedence recently.

**Comment by LindsayMacfarlane** [comment]
Thanks for that clarification @davidclaveau ! I've moved this ticket back into Todo :)

**Comment by davidclaveau** [comment]
After review, we're aiming to make the notes section follow this data pattern:

#### Primary key:
- pk: `notes::[orcs]`
- sk: `[ISO timestamp]`

This will allow us to easily pull all notes from the database for a specific park, and sort the notes by when they were created, avoiding any collisions.

#### Global Secondary Index:
- gsi pk: `[user/userID]`
- gsi sk: `[ISO timestamp]`

It benefits us to have a GSI using a user id (or other user-specific identifier), which should allow us to sort notes by user, filter which parks and subareas a user's has notes, and provide some access control for notes (editing/deleting only the user's notes).

**Comment by LindsayMacfarlane** [comment]
Thank you for all your work on this one @davidclaveau ! In one of our future check-ins, it would be great if you could walk me through the data model for A&R :)
