### ISSUE TITLE
[L] Update AR admin UI, tokens and admin library

### ISSUE THREAD

**Issue by Dianadec** [bcgov/bcparks-ar-admin#335]
#### Description:

Updating A&R admin to match the figma that has the admin library and tokens applied.

#### Acceptance Criteria:
Attendance and Revenue UI matches figma and uses the colours, fonts, sizes and styling from the Admin Library

#### Development Checklist:

- [ ] Updated Bootstrap library is imported
- [ ] Components are updated to use bootstrap standard where possible 
- [ ] UI matches [A&R Figma](https://www.figma.com/design/yoMhvO0KZvsM6qoqwuIjpt/Attendance-%26-Revenue?node-id=559%3A3339&t=w1Iw55Z6TSmLEK9U-1)

#### Dependencies

- Blocked by [#468](https://github.com/bcgov/parks-data-register/issues/468), [#315](https://github.com/bcgov/parks-data-register/issues/315)
- Blocking

**Relevant documentation as reference**

[Tokens overview](https://www2.gov.bc.ca/gov/content/digital/design-system/foundations/design-tokens#overview)
[Token glossary](https://www2.gov.bc.ca/gov/content/digital/design-system/foundations/design-tokens/glossary)
[A&R Figma](https://www.figma.com/design/yoMhvO0KZvsM6qoqwuIjpt/Attendance-%26-Revenue?node-id=559%3A3339&t=w1Iw55Z6TSmLEK9U-1)

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by meredithom** [comment]
Only colours, fonts, sizes and styling updated, components will need to be updated as necessary after the figma library is updated  [#315](https://github.com/bcgov/parks-data-register/issues/315)

**Comment by meredithom** [comment]
Looks good, a few things to check/fix before it goes to prod:

- Breadcrumb background is missing. Should match Admin Library Figma:
![Image](https://github.com/bcgov/bcparks-ar-admin/assets/15185966/ced70a75-1757-43c8-9343-8e9b28b430e9)

- Accordions have a header colour when expanded now, should be removed if possible 
- Info icons are too large on the input forms pages, the text and icon should be the same colour (secondary text: #474543)
- Form padding and spacing is off, for now only the colours should be updated
- The tabs on the export page are missing borders, should look like:
![Image](https://github.com/bcgov/bcparks-ar-admin/assets/15185966/a8d7e06e-f831-42e0-b7e5-ac4c7c297f1b)

**Comment by manuji** [comment]
Tested on TEST: **Failed**
* The Export report page still missing the borders.

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this issue has been fixed. Thanks @danieltruong .
* Passing to PO review.

**Comment by meyerdarcie** [comment]
Moving to done.
