### ISSUE TITLE
Designs: Add Date Range search/filter to export data page

### ISSUE THREAD

**Issue by meyerdarcie** [bcgov/bcparks-ar-admin#338]
#### Description:

This ticket is to create any relevant designs for adding Date Range search/filter to export data page in A&R. 

Refinement Notes:

99% of the time the export is just for the most recent data.
Prefers to export a set of months (eg: Jan-March as an example of a set)
Rarely would they need to export the whole thing
Ideal: Specify months. April data; May Data, etc
Remove Export all or no? - New staff might not know when the data starts... eg: January 2017 is when the data first starts
Keep Export All

If we need more clarification, let's contact Sally.

#### Acceptance Criteria:

- [x] designs for adding Date Range search/filter are in figma and linked here 

#### Dependencies
- blocks #254 

**Relevant documentation as reference**
- see #254 

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by JLWade** [comment]
Notes from refinement May 28th, 2029:
- will likely be mostly back end work - may not have this functionality built yet in the export feature

**Comment by meredithom** [comment]
[Figma Design-frame 1](https://www.figma.com/design/yoMhvO0KZvsM6qoqwuIjpt/Attendance-%26-Revenue?node-id=5832-7852&t=fSYcJay9Akw3JRTp-4)

[Figma Design-frame 2](https://www.figma.com/design/yoMhvO0KZvsM6qoqwuIjpt/Attendance-%26-Revenue?node-id=5833-9348&t=fSYcJay9Akw3JRTp-4)

Notes: 
- the filter should only be available if Export All is unchecked. 
- Prototype for dropdown behaviour is unavailable

**Comment by meyerdarcie** [comment]
Designs look good - moving to done.
