### ISSUE TITLE
A&R -> Improve Variance Report

### ISSUE THREAD

**Issue by Dianadec** [bcgov/bcparks-ar-admin#352]
#### Description:

Improve Variance Report 
- Currently report cannot replace manual variance checks in excel to analyze state of data.  
- Is not readable enough to send to regional staff & POs 
- Needs- column for each category, the comparison numbers, replace back-end category names with category names used in the UI. 

June 12/24 notes: 
- Doesn’t currently export in a readable way 
- Need to check 3 places – check variance report, review screen to see what the values are,  
- Want to do review process start to finish in the review screen then you can send someone the variance report 

This point below is covered in ticket #357 
- The variances are all listed together in one cell per activity - ideally each type of variance would get it’s own column, with a user-friendly category name (for example “SSCFE Camping Party Nights” instead of “campingPartyNightsAttendanceSocial”). 
![Image](https://github.com/user-attachments/assets/94b1c710-20f1-41a9-967e-09d8de0baa8d)

#### Acceptance Criteria:

Given
When
Then 

Given
When
Then

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking
- May be related to # https://github.com/bcgov/bcparks-ar-api/issues/234

**Wireframe(s):**

**Workflows:**

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by sallyhaynes** [comment]
Ticket #357 takes care of the "each category having it's own column" request

**Comment by Dianadec** [comment]
@davidclaveau is this ticket considered done since some of the work was captured in 357? cc @meyerdarcie

**Comment by davidclaveau** [comment]
@Dianadec correct! This is done and should be closed 😄

**Comment by meyerdarcie** [comment]
Moving to done, thanks @davidclaveau
