### ISSUE TITLE
[L] A&R SAM front end deployment (admin)

### ISSUE THREAD

**Issue by meyerdarcie** [bcgov/bcparks-ar-admin#359]
#### Description:

Goal is to be able to deploy A&R via SAM without the use of any terraform.

**Acceptance criteria**

- [ ] Everything that is AWS side will need to be setup using SAM:
  - [ ] Cloudformation
  - [ ] Cloudwatch
  - [ ] S3
- [ ] All tests pass
- [ ] GitHub Actions deploys successfully to dev, test, prod
- [ ] Terraform is completely removed
- [ ] Old, non-SAM code is removed
- [ ] Full smoke test to make sure everything ported over properly

#### Development Checklist:

- [ ] All tests are converted to work with the SAM changes, this mean path changes and conversion(s) for layers
- [ ] All tests run successfully and pass
- [ ] Update READMEs accordingly

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- Look at data register admin as example
-

**Comment by davidclaveau** [comment]
@manuji this is now ready to be moved into TEST and smoked 🏕 !

I went through some debugging with the deployment in DEV and applied the changes in GitHub Actions so it _shouldn't_ fail when going into TEST, but I'll believe it when I see it 😅 

Once it's deployed, I just have to make a small change so the new vanity url `test-ar.bcparks.ca` is connected, but then once that propagates it'll be good to go!

Let me know if you have any questions!

**Comment by manuji** [comment]
Tested on TEST: **Pending**
* Verified that both urls to the test environment are working. 

@davidclaveau , one question: when I am on the home page the url shows too much information, and wondering if that's something we can fix?

eg: https://test-ar.bcparks.ca/#iss=https://test.loginproxy.gov.bc.ca/auth/realms/bcparks-service-transformation

![Image](https://github.com/user-attachments/assets/36a2d5c6-80ea-4c23-b9bc-3365267d35e1)

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* verified that this task has been completed and the vanity url is working. 
* Passing to PO review.

**Comment by manuji** [comment]
Deployed to PROD.

**Comment by JLWade** [comment]
took a quick look in test and admin FE looks good - moving to done
