### ISSUE TITLE
[XS] [A&R Feature Request] Increase allowable character limit for variance notes field

### ISSUE THREAD

**Issue by sallyhaynes** [bcgov/bcparks-ar-admin#361]
#### Description: 
 
As an admin, I want to be able to add more information into the variance notes field to better capture variance data over time. 
 
Increase variance note field to be able to hold more than one hundred characters - up to 200 characters.
 
#### Acceptance Criteria:
 
Given I am an admin
When I am entering variance notes into the variance notes field
Then I can include up to **200 characters**
 

#### Development Checklist:
 
- [ ] Increase allowable text limit in variance notes field
- [ ] ...
- [ ] ...
 
#### Dependencies
 
- Blocked by
- Blocking
 
**Wireframe(s):**
 
 
**Workflows:**
 
 
**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)
 
- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)
 
**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner
 
#### Notes:
- Context: Common request from POs and staff. Can be difficult to explain a variance with only one hundred characters, especially if there is more than one reason. Expanding the allowed # of characters will allow more thorough explanations of data anomalies.  

![image](https://github.com/user-attachments/assets/e37ba773-cbda-45d3-97bb-57800d69a2f2)

**Comment by LindsayMacfarlane** [comment]
October 11, 2024 prioritization session:

- this request was highlighted as a med-priority. 
-  field is currently limited to 100 characters which isn't enough space to write notes
- A&R team don't need space for a novel, but would like to see limit increased.

**Comment by Dianadec** [comment]
This could substitute for a drop-down for now. Context: If there are multiple reasons for the variance, they can't time them in.

**Comment by manuji** [comment]
Tested on TEST: **Passed**. 
* Verified that the Variance field now set to 200 characters.
* Verified that the character count is updated to 0/200. 
* Verified that the Variance report and Standard report shows the notes correctly. 
* Verified when the character limit is exceeded validation styles are applied, but the validation error message "This field is too long" and the red border around the field is only displayed if the user clicks outside of the text field. It would be ideal if the user knows they exceeded the character limit while they type. Not a blocker but good for better user experience. 
* Passing this to PO review @LindsayMacfarlane . 
https://github.com/user-attachments/assets/c76631b0-bcc7-4f69-b1ec-2c5a23a5d6d5

**Comment by LindsayMacfarlane** [comment]
1. First test in A&R test environment gave me the following:
![Image](https://github.com/user-attachments/assets/4d925519-8b07-492d-9e02-ba70fa4a3f2a)

Enter data > Date (2024-08) > Park (Strathcona - Lindsay's Loop) > Subarea (Buttle Lake)

2. Cleared cache and tried again. Still limited to 100 characters.
![Image](https://github.com/user-attachments/assets/6ce5df32-df65-4453-be70-869852da26b3)

@manuji @cameronpettit - am I doing something wrong?

**Comment by manuji** [comment]
@LindsayMacfarlane looks like there is an issue with the vanity urls we are using. I tested on the url : https://test-ar.bcparks.ca/ and you might have used the old url : https://d3ahrzu0mpndj3.cloudfront.net/enter-data. I am not sure why those two urls give different behaviours when both suppose to redirect us to the A&R test environment. Could you please verify on https://test-ar.bcparks.ca/ ? 

@davidclaveau & @cameronpettit , could you please help us figure out the issue with the urls? Should we stop using the old url?

**Comment by LindsayMacfarlane** [comment]
Re-tested using the new url provided above. Passed. Moving ticket to done.

Thank you to everyone who worked on implementing and testing this work!
