### ISSUE TITLE
A&R: Add sub-area to Stein Valley Nlaka'pamux Heritage Park

### ISSUE THREAD

**Issue by nicolebottoms** [bcgov/bcparks-ar-admin#362]
#### Description:

This ticket is to add a sub-area to Stein Valley Nlaka'pamux Heritage Park, called Lytton Trailhead. 

Changes:
- ORCS Number: 9458
- Region: Thompson Cariboo
- Section: Thompson
- Management Area: Thompson Southern Rivers
- Bundle: N/A
- Park: Stein Valley Nlaka'pamux Heritage Park
- Park Sub Area:  Lytton Trailhead

#### Acceptance Criteria: ####

- [ ] Add sub-area called "Lytton Trailhead"
- [ ] Add day use in order to enter trail counter data 

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by meredithom** [comment]
**Refinement Notes:**
- TODO: Find sub-area spreadsheet and create a template for new sub-area entry

**Comment by davidclaveau** [comment]
New template created in #383 

Form in CHEFS: https://submit.digital.gov.bc.ca/app/form/submit?f=8de4495a-c8f9-4775-aafb-789a8bee64ed

**Comment by davidclaveau** [comment]
@manuji this is now available in TEST.

It's just a simple`post` request to the  `/subarea` endpoint, so there's no code or deployment needed. As long as the Subarea exists and passed your smoke tests on TEST, then I can do the same on prod 😄

Let me know if anything looks amiss!

**Comment by manuji** [comment]
Tested on TEST: **Pending**
* Verified that the subArea has been added to the two pages Enter data and Review data filter field. 
* Verified that DynamoDB parkAR table has been updated with the new SubArea.
* But, the exported report does not show this new subArea when data entered in to the DatUse Facility. -> @davidclaveau , do you know a reason why I don't see this Park/SubArea in the exported report?

**Comment by davidclaveau** [comment]
@manuji good spot on this! Looks like I forgot to change Stein Valley Nlaka'pamux Heritage Park to no longer be `legacy` with its new subarea. 

Anything that has `legacy == true` is skipped during Export, so it wasn't getting pulled into the file when it was calculating and exporting the data. I changed that now and I'll make note for the prod update so that doesn't happen again 😄

**Comment by manuji** [comment]
Thank you @davidclaveau , I will check and let you know the status. :)

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this issue has been fixed.
* Passing to PO review.

**Comment by manuji** [comment]
@davidclaveau , this ticket is ready to be worked on the PROD environment.

**Comment by JLWade** [comment]
looks good moving to done
