### ISSUE TITLE
Cannot export the variance report for the fiscal year March 2024- April 2025

### ISSUE THREAD

**Issue by manuji** [bcgov/bcparks-ar-admin#363]
Scenario:
* Navigate to the A&R on TEST environment: https://d3ahrzu0mpndj3.cloudfront.net/export-reports
* Navigate to the export report page and then select the tab to export the Variance report. 
* Try to export the report for the fiscal year March 2024-April 2025 to check the variances for the current month August 2024. 

Expected:
* users can export a variance report for past years and current fiscal year (even if we are only part way through current fiscal year)
* users cannot export a variance report for fiscal years that have not yet started

Issue:
* The Variance export doesn't give the option to pick the current fiscal year to export the report. 

![Image](https://github.com/user-attachments/assets/f99e7e88-2e02-4cc1-8ff4-cbb809c9ce9a)

**Comment by davidclaveau** [comment]
@manuji this is ready for review!

**Comment by manuji** [comment]
Testing blocked as the exported report does not show for the Variance tab @davidclaveau

**Comment by davidclaveau** [comment]
@manuji this fix is in DEV now!

**Comment by manuji** [comment]
Tested on TEST: Passed
* Verified that this issue has been fixed. 
* Moving to Done
