### ISSUE TITLE
A&R: update to "Marine Sites" sub-areas

### ISSUE THREAD

**Issue by nicolebottoms** [bcgov/bcparks-ar-admin#368]
#### Description:

This ticket is to combine the following sub areas into one called "Marine Sites"

Changes:

- ORCS Number: 0001
- Region: West Coast
- Section: North Island
- Management Area: Strathcona
- Bundle: Strathcona (Frontcountry)
- Park: Strathcona
- Park Sub Area:
- Mount Titus
- 0415
- Phillips Creek
- 0417
- Wolf River
- 0425
- Rainbow Island
- 0418
- Upper Campbell
- 0424

#### Acceptance Criteria: ####

- [ ] Sub areas are combined into one called "Marine Sites"
- [ ] Notify Hailey when complete

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by davidclaveau** [comment]
@manuji this migration is ready for TEST. I've run it locally and in DEV and it looks like everything is working as expected 😄 

Once this is in TEST, I'll just need to create the new "Marine Sites" subarea and then run the migration against it. Then it should be good for smoke testing!

The outcome is that Mount Titus, Phillips Creek, Wolf River, Rainbow Island, and Upper Campbell will all have their records combined into this "Marine Sites" subarea (it's just for Backcountry Camping - so `People` and `Gross Camping Revenue` will be added up across the old subareas).

The old subareas will then get their "historical" tag and all be locked, but still visible in the admin. The `variance` records tied to these old subareas will _not_ be combined for Marine Sites, so Marine Sites won't have any variance records tied to them even if the old subareas might have. This is expected and has been cleared by Nicole and Sally!

Let me know if you have any questions!

**Comment by davidclaveau** [comment]
I made a [PR for the frontend](https://github.com/bcgov/bcparks-ar-admin/pull/387) to show `grossCampingRevenue` data items when a record is legacy/historic.

Seems like this was initially a business decision to only show `people` data items for legacy records, as legacy records could be vastly different. Doesn't show any issues with adding `grossCampingRevenue` data for these new legacy records, or any past legacy records.

![Image](https://github.com/user-attachments/assets/7b2849f4-0362-4f34-b54a-623a6a7f25b5)

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that by the migration the new Marine Sites subArea has been added with the facility "Backcountry Camping".
* Verified that the data from individual subAreas mentioned in the ticket description are now added and displayed under the new subArea.
* Verified that the previously active SubAreas now part of the Marine Sites are all marked as "historical" subAreas.
* Verified that the new "Marine Sites" display data in the exported report. 

**Notes**:
* Currently the "marine sites" subArea is locked as a security measure and this can be adjusted by @davidclaveau .
* The subAreas marked with "historical" do not display the data for "Gross Camping Revenue" field and as per @davidclaveau 's findings, it happens when a record is marked as isLegacy=true. 
eg:
![Image](https://github.com/user-attachments/assets/7a484305-ab54-49d3-baba-24557493e6f9)

Passing to PO review.

**Comment by JLWade** [comment]
moving to done and data change can be updated in prod
