### ISSUE TITLE
Bug: PO experiencing "error getting park"

### ISSUE THREAD

**Issue by meyerdarcie** [bcgov/bcparks-ar-admin#371]
**Describe the bug**
PO is attempting to input data for June and July and getting an error message that reads "error getting park". 

- getting error intermittently
- PO refreshed, attempted in chrome/edge and cleared cache 
- was able to input data @ 4:30pm on Aug. 28th, but could not enter data in morning of Aug. 29th 

**To Reproduce**
1. Go to A&R admin
2. Error message pops up right away before even clicking enter data 
3. When navigating to enter data page, error persits and no parks show up to select from

**Expected behavior**

- PO should be able to log into A&R and click enter data and select desired park to then enter data. 

**Screenshots**
![Image](https://github.com/user-attachments/assets/514ba03c-0cba-4d07-8dc8-070a1cf1b742)

https://photos.onedrive.com/share/93463B36C24F3C10!25753?cid=93463B36C24F3C10&resId=93463B36C24F3C10!25753&authkey=!AO2DrLgRGBKMKEw&ithint=video

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by meyerdarcie** [comment]
@davidclaveau FYI on this bug ticket from yesterday - PO was able to enter data yesterday around 4:30pm, but experienced issues again this morning.

**Comment by meyerdarcie** [comment]
@danieltruong @cameronpettit @davidclaveau - FYI Cory will be logging in under the name "Janice Trottier", which from the video above does display when he gets to the enter data screen - I'll update this when I have more info on when they were experiencing the issue.  



![Image](https://github.com/user-attachments/assets/43648562-847a-4c58-a7b4-dd043f223dc8)

**Comment by meyerdarcie** [comment]
Update from the PO - FYI @danieltruong @cameronpettit @davidclaveau 

- able to see the name prior to the error (page is trying to load), and after closing the error message 
- using BCEID to log in, which is associated with office8888@telus.net
- Experienced the error Thursday, Aug 29 7:57 AM, and Friday Aug 30 at 9:30 AM on edge and chrome

**Comment by davidclaveau** [comment]
@manuji this update is in DEV now, but is really just a background change to the functions and their responsiveness/speed. Let me know if you have any questions!

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that no error messages displayed when trying to add data to the "Enter Data" page. 
* Moving to PO review..

**Comment by meyerdarcie** [comment]
Excellent - moving to done.
