### ISSUE TITLE
A&R: Create/update process for submitting new Park Subareas

### ISSUE THREAD

**Issue by davidclaveau** [bcgov/bcparks-ar-admin#383]
#### Description:

This ticket is to create/update the current process for adding new Park Subareas to A&R to alleviate any data entry issues or back and forth from missing data sets.

#### Acceptance Criteria: ####

- [x] Create a "checklist" to ensure all required data is present in a Subarea submission

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

- Relevant excel spreadsheet: [Park Name Comparisons - with sub-area codes](https://bcgov.sharepoint.com/:x:/r/teams/031072/Shared%20Documents/Attendance%20and%20Revenue/Park%20Name%20Comparisons%20-%20with%20sub-area%20codes.xlsx?d=wb20921a6a83a44199d64714e7caf76e0&csf=1&web=1&e=zz4WZx)
- Could possibly use [CHEFS](https://digital.gov.bc.ca/bcgov-common-components/common-hosted-form-service/)

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by davidclaveau** [comment]
Created a new form template in CHEFS: https://submit.digital.gov.bc.ca/app/form/submit?f=8de4495a-c8f9-4775-aafb-789a8bee64ed

**Comment by davidclaveau** [comment]
@meyerdarcie not sure if you wanted to provide a final sign-off for this, but looks like it got the OK from Sally and Nicole 😁

**Comment by meyerdarcie** [comment]
Looks great and sounds like it's working for Sally and Nicole so moving to done :)
