### ISSUE TITLE
Accordion arrows initialize up

### ISSUE THREAD

**Issue by danieltruong** [bcgov/bcparks-ar-admin#53]
Accordion arrows are initializing up like the following:

![image](https://user-images.githubusercontent.com/10578223/164507541-dfdc2b03-d83c-4484-b558-542ea3551f36.png)

They should be initialized down:

![image](https://user-images.githubusercontent.com/10578223/164507612-d49b4ed7-ef49-489e-9f0d-8ca6164c033c.png)

You are able to get them to point down. To do that, you have to open and close them again.

**Comment by cameronpettit** [comment]
first

**Comment by danieltruong** [comment]
Resolved in [49cc616](https://github.com/bcgov/bcparks-ar-admin/commit/49cc61674d2361e18dc479d123049a524f517286)
