### ISSUE TITLE
Quantitative fields are returning type: string when they should return type: number

### ISSUE THREAD

**Issue by cameronpettit** [bcgov/bcparks-ar-admin#62]
When passing input field types from parent to child, the child input field is not accepting type `number`.

In Parent:
```
<child [type]="'number'"></child>
```

In Child:
```
@Input() type: string = 'text' // text, number

======

<input type={{ type }}></input>
```

Input type is not resolving correctly, resulting in fields being cast as strings by default.

**Comment by meredithom** [comment]
https://github.com/angular/angular/issues/13243
