### ISSUE TITLE
Form does not prepopulate when sharing url

### ISSUE THREAD

**Issue by cameronpettit** [bcgov/bcparks-ar-admin#64]
Form prepopulation currently pulls existing form data from the same data pool as the accordions use. When sharing a form via url, the form is accessed without the accordion being previously loaded, so the form does not prepopulate.

Likely will have to introduce an (optional?) API call when navigating to form pages.

**Comment by danieltruong** [comment]
A similar action is already happening on the enter-data page. Take a look at how the sub-area resolver works with the sub-area-search component.
